title: Settings
data:
  site_name: 'Yiddishe Kop'
  personality: formal
  show_signup: true
  social:
    -
      name: Github
      url: 'https://github.com/Yiddishe-Kop'
      icon: site/social-icons/github.svg
    -
      name: Email
      url: 'mailto:yehuda@yiddishe-kop.com'
      icon: site/social-icons/email.svg
